### ISSUE TITLE
Left & Right Limit Support

### ISSUE THREAD

**Issue by RHarr6306** [Le-SirH/calculus#7]
Users may be able to make left and right hand limit calculations instead of calculating both sides.

**Comment by RHarr6306** [comment]
NOTE: When a function such as 1/((x-3)^20 is entered into the limit calculator, there is no output. The right and left hand limits are the same (infinity) but there is no function that returns infinity if it is detected.

**Comment by Le-SirH** [comment]
Additionally, support for infinite limits could be an option as well.
